import json
import time
import sys

from argparse import ArgumentParser, Namespace
from pathlib import Path

sys.path.append(str(Path(__file__).parent))

try:
    from . import mas_autocomplete
    from .ansyas import Ansyas
except ImportError:
    import mas_autocomplete
    from ansyas import Ansyas


def main(args: Namespace) -> None:

    # arguments passed via command line
    mas_path = args.mas
    solution_type = args.solution_type
    operating_point_index = args.operating_point_index
    output_folder = args.output
    project_name = args.project_name
    aedt_version = args.aedt_version
    non_graphical = args.ng
    new_desktop_session = args.new_desktop
    simulate = args.run_simulation

    ansyas = Ansyas(number_segments_arcs=args.number_segments_arcs,
                    initial_mesh_configuration=args.initial_mesh_configuration,
                    maximum_error_percent=args.maximum_error_percent,
                    refinement_percent=args.refinement_percent,
                    scale=args.scale,)

    f = mas_path.open("r")
    mas_dict = json.load(f)
    mas = mas_autocomplete.autocomplete(mas_dict)

    # check that the operating point index is valid for the given MAS file
    assert operating_point_index < len(mas.inputs.operatingPoints), f"Operating point {operating_point_index} is not present on inputs, which only have {len(mas.inputs.operatingPoints)} points"

    # if project name is not provided, try to get it from the manufacturer info reference in the MAS file.
    # If that is not available, default to the name of the MAS file itself.
    if not project_name:
        try:
            project_name = f"{mas_dict['magnetic']['manufacturerInfo']['reference']}_{time.time()}"
        except (TypeError, KeyError):
            base_name = mas_path.stem
            project_name = f"{base_name}_{time.time()}"

    print("output_folder")
    print(output_folder)
    print("project_name")
    print(project_name)

    project = ansyas.create_project(
        outputs_folder=output_folder,
        project_name=project_name,
        specified_version=aedt_version,
        non_graphical=non_graphical,
        solution_type=solution_type,
        new_desktop_session=new_desktop_session
    )
    ansyas.set_units("meter")
    ansyas.create_magnetic_simulation(
        mas=mas,
        simulate=simulate,
        operating_point_index=operating_point_index
    )
    project.release_desktop(close_projects=args.close_projects, close_desktop=args.close_desktop)


if __name__ == "__main__":

    # default command line arguments
    default_mas = Path(__file__).resolve().parents[2] / "examples" / "concentric_transformer.json"

    parser = ArgumentParser(
        prog='Ansyas MAS Loader',
        description='Create Magnetic Component Models with Ansyas using MAS JSON files generated by OpenMagnetics',
        epilog='Copyright (c) 2026 Würth Elektronik eiSos GmbH & Co. KG.')
    parser.add_argument("--mas",
                        type=Path,
                        required=False,
                        default=default_mas,
                        help='MAS configuration file created by OpenMagnetics.'
                             'Default is concentric_transformer.json in the examples folder of this repository.'
                             'Note that the full path to the MAS file must be provided if it is not in the same directory as this script.'
                             ' Example: python ansyas_mas_loader --mas example.json')

    parser.add_argument("--solution_type",
                        type=str,
                        required=False,
                        default="EddyCurrent",
                        help='Specify AEDT\'s solution type to run. Default is EddyCurrent. '
                             'Options are SteadyState, EddyCurrent, AC Magnetic, Transient, TransientAPhiFormulation.')

    parser.add_argument("--aedt_version",
                        type=str,
                        required=False,
                        default="2025.2",
                        help='Specify AEDT version number in format <year>.<release>. '
                             'For example: 2025R1 is 2025.1.')

    parser.add_argument("--ng",
                        type=bool,
                        required=False,
                        default=False,
                        help='Non-graphical mode.')

    parser.add_argument("--new_desktop",
                        type=bool,
                        required=False,
                        default=False,
                        help='Initialize a new AEDT instance.')

    parser.add_argument("--number_segments_arcs",
                        type=int,
                        required=False,
                        default=12,
                        help='Number of segments in curve surfaces.')


    parser.add_argument("--initial_mesh_configuration",
                        type=int,
                        required=False,
                        default=2,
                        help='Mesh Configuration defaults to 2.')

    parser.add_argument("--maximum_error_percent",
                        type=int,
                        required=False,
                        default=5,
                        help='Maximum error tolerance in percent. Defaults to 5%.')


    parser.add_argument("--refinement_percent",
                        type=int,
                        required=False,
                        default=5,
                        help='Energy based mesh refinement. Defaults to 5%.')

    parser.add_argument("--scale",
                        type=int,
                        required=False,
                        default=1,
                        help='Model scale. Defaults to 1.')

    parser.add_argument("--operating_point_index",
                        type=int,
                        required=False,
                        default=0,
                        help='Operating point index can be specified from the MAS file.'
                             'Default is 0, which will take the first operating point in the MAS file.')

    parser.add_argument("--run_simulation",
                        type=bool,
                        required=False,
                        default=False,
                        help='Run simulation after setup.Defaults to False')


    parser.add_argument("--close_desktop",
                        type=bool,
                        required=False,
                        default=False,
                        help='Close AEDT desktop after finishing. Defaults to False.')

    parser.add_argument("--close_projects",
                        type=bool,
                        required=False,
                        default=False,
                        help='Close AEDT project after finishing. Defaults to False.')

    parser.add_argument("--output",
                        type=Path,
                        required=False,
                        default=Path().cwd()/"output",
                        help='Output directory where results are stored.'
                             'Default is the current working directory.')

    parser.add_argument("--project_name",
                        type=str,
                        required=False,
                        help='Output directory where results are stored.'
                             'If not defined, it will try to the manufacturer info reference in the MAS file.'
                             'If the MAS file does not have this information, '
                             'it will default to the name of the MAS file itself.')

    args = parser.parse_args()
    main(args)
