import json
import os
import time
import sys

sys.path.append(os.path.dirname(__file__))
from argparse import ArgumentParser, Namespace
from pathlib import Path

try:
    from . import mas_autocomplete
    from .ansyas import Ansyas
except ImportError:
    import mas_autocomplete
    from ansyas import Ansyas


def main(args: Namespace) -> None:

    # arguments passed via command line
    mas_path = args.mas
    solution_type = args.solution_type
    operating_point_index = args.operating_point_index
    output_folder = args.output
    project_name = args.project_name

    non_graphical = False
    new_desktop_session = False
    ansyas = Ansyas(number_segments_arcs=12, initial_mesh_configuration=2, maximum_error_percent=5, refinement_percent=5, scale=1)

    f = mas_path.open("r")
    mas_dict = json.load(f)
    mas = mas_autocomplete.autocomplete(mas_dict)

    # check that the operating point index is valid for the given MAS file
    assert operating_point_index < len(mas.inputs.operatingPoints), f"Operating point {operating_point_index} is not present on inputs, which only have {len(mas.inputs.operatingPoints)} points"

    # if project name is not provided, try to get it from the manufacturer info reference in the MAS file.
    # If that is not available, default to the name of the MAS file itself.
    if not project_name:
        try:
            project_name = f"{mas_dict['magnetic']['manufacturerInfo']['reference']}_{time.time()}"
        except (TypeError, KeyError):
            base_name = mas_path.stem
            project_name = f"{base_name}_{time.time()}"

    print("outputs_folder")
    print(output_folder)
    print("project_name")
    print(project_name)

    project = ansyas.create_project(
        outputs_folder=output_folder,
        project_name=project_name,
        # specified_version="2023.2",
        non_graphical=non_graphical,
        solution_type=solution_type,
        new_desktop_session=new_desktop_session
    )
    ansyas.set_units("meter")
    ansyas.create_magnetic_simulation(
        mas=mas,
        simulate=False,
        operating_point_index=operating_point_index
    )
    project.release_desktop(close_projects=False, close_desktop=False)


if __name__ == "__main__":

    # default command line arguments
    default_mas = Path(__file__).resolve().parents[2] / "examples" / "concentric_transformer.json"

    parser = ArgumentParser(
        prog='Ansyas MAS Loader',
        description='Create Magnetic Component Models with Ansyas using MAS JSON files generated by OpenMagnetics',
        epilog='Copyright (c) 2026 Würth Elektronik eiSos GmbH & Co. KG.')
    parser.add_argument("--mas",
                        type=Path,
                        required=False,
                        default=default_mas,
                        help='MAS configuration file created by OpenMagnetics.'
                             'Default is concentric_transformer.json in the examples folder of this repository.'
                             'Note that the full path to the MAS file must be provided if it is not in the same directory as this script.'
                             ' Example: python ansyas_mas_loader --mas example.json')

    parser.add_argument("--solution_type",
                        type=str,
                        required=False,
                        default="EddyCurrent",
                        help='Specify AEDT\'s solution type to run. Default is EddyCurrent. '
                             'Options are SteadyState, EddyCurrent, AC Magnetic, Transient, TransientAPhiFormulation.')

    parser.add_argument("--operating_point_index",
                        type=int,
                        required=False,
                        default=0,
                        help='Operating point index can be specified from the MAS file.'
                             'Default is 0, which will take the first operating point in the MAS file.')

    parser.add_argument("--output",
                        type=Path,
                        required=False,
                        default=Path().cwd()/"output",
                        help='Output directory where results are stored.'
                             'Default is the current working directory.')

    parser.add_argument("--project_name",
                        type=str,
                        required=False,
                        help='Output directory where results are stored.'
                             'If not defined, it will try to the manufacturer info reference in the MAS file.'
                             'If the MAS file does not have this information, '
                             'it will default to the name of the MAS file itself.')

    args = parser.parse_args()
    main(args)
